name: delta_markdown
version: 0.2.0

description: A library for converting between Delta and Markdown.
homepage: https://github.com/friebetill/notus_markdown

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  args: ^2.0.0
  charcode: ^1.2.0
  collection: ^1.15.0
  flutter_quill:
    git:
      url: https://github.com/phuongtinhbien/flutter-quill.git
      ref: fix2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  pedantic: ^1.11.0
  test: ^1.2.0